[project]
authors = [{ name = "Danil Akhtarov", email = "daxartio@gmail.com" }]
dependencies = ["typing-extensions>=4.5,<5"]
description = "Easy contextual information logging"
keywords = ["contextvar", "logging", "context-logging"]
license = { file = "LICENSE" }
name = "kontext"
readme = "README.md"
requires-python = ">=3.10,<4"
version = "1.3.0"

[project.urls]
Changelog = "https://github.com/daxartio/kontext/blob/main/CHANGELOG.md"
Homepage = "https://pypi.org/project/kontext"
Repository = "https://github.com/daxartio/kontext"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true

[[tool.mypy.overrides]]
disallow_incomplete_defs = false
disallow_untyped_defs = false
module = ["tests.*", "examples.*"]

[tool.coverage.run]
branch = true
omit = [
  "tests/*",
  "**/__main__.py",
  "**/.venv/*",
  "**/site-packages/*",
  "examples/*",
]

[tool.coverage.report]
fail_under = 100
show_missing = true
skip_covered = true

[tool.pytest.ini_options]
addopts = "--strict-markers --showlocals --verbosity 2"
asyncio_mode = "strict"
log_level = "DEBUG"

[dependency-groups]
dev = [
  "mypy>=1",
  "pytest>=9",
  "pytest-asyncio>=1.3",
  "pytest-cov>=7",
  "pytest-mock>=3",
  "ruff>=0.14",
  "toml>=0.10",
]
